fix(points): remove quotes before search for thank
devcord/points pull request #14
Opened 2020-09-10 06:58 UTC by nsebs

This RP corrects the issue of users giving unintentional thanks because they quote a message with thanks on it. For example:

<pre>
> So no one can help ... thanks anyways
@user sorry not really sure what you are asking
</pre>

2020-09-23 21:25 UTC, lostdesign commented
@austinmccalley can you check?

2020-09-24 19:42 UTC, austinmccalley requested changes
The initial code is there, can you please add some comments for better readability and maintainability for future developers.

2020-09-24 21:32 UTC, austinmccalley approved these changes

2020-09-24 21:32 UTC, merged

2020-09-24 21:38 UTC, nsebs commented
:tada: